version: "3"
services:
  notes:
    build : ./microservice_AffichageNotes
    links:
      - mysql
    ports:
      - "5001:5000"
    restart: always
  connexion:
    build : ./microservie_Connexion
    links:
      - mysql
      - notes
    ports:
      - "5000:5000"
    restart: always
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oooo
      MYSQL_DATABASE: projet_devops
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  
  adminer:
      image: adminer
      restart: always
      ports: 
        - 8080:8080