version: "3"
services:
  notes:
    build : ./microservice_AffichageNotes
    hostname: notes
    ports:
      - 5001:5001  # host:contai                             
    networks:
      sample :
        aliases :
          - notes
    restart: always
  connexion:
    build : ./microservie_Connexion
    hostname: connexion
    ports:
      - "5000:5000"
    networks:
      sample:
        aliases:
          - connexion
    links :
      - notes
    restart: always
  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "30000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: oooo
      MYSQL_DATABASE: projet_devops
    restart: always
    hostname: mysql
    networks:
      sample:
        aliases:
          - mysql
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  
  adminer:
      image: adminer
      restart: always
      ports: 
        - 8080:8080
networks:
  sample: 
